// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDfj86bN4_KONE09OLMAv6EJ8m-V_uI1s',
    appId: '1:990054144807:android:a139a4875d05d544e86702',
    messagingSenderId: '990054144807',
    projectId: 'conectacampo-16a33',
    storageBucket: 'conectacampo-16a33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw-ilBCRNX3nRC_Y9QTv6Oi--J1YXdYgI',
    appId: '1:990054144807:ios:86c13bee711e8f2de86702',
    messagingSenderId: '990054144807',
    projectId: 'conectacampo-16a33',
    storageBucket: 'conectacampo-16a33.appspot.com',
    androidClientId: '990054144807-3tafomusq8frqcs9rbap16mu5ml7tj2l.apps.googleusercontent.com',
    iosClientId: '990054144807-51l470es7dnvppkb3mgtfvtk9bre4s3o.apps.googleusercontent.com',
    iosBundleId: 'br.com.conectacampo',
  );
}
